server:
  port: 9010

spring:
  application:
    name: vwr_flow

  data:
    redis:
      host: localhost
      port: 6379
  task:
    scheduling:
      pool:
        size: 3
scheduler:
  enable: true

---

spring:
  config:
    activate:
      on-profile: test

  data:
    redis:
      host: localhost
      port: 63790


scheduler:
  enable: false